    SELECT 
        APPOINTMENT_ID,
        PATIENT_ID,
        DOCTOR_ID,
        BRANCH_ID,
        CASE 
            WHEN APPOINTMENT_DATE<=CURRENT_DATE THEN APPOINTMENT_DATE
            ELSE NULL
        END APPOINTMENT_DATE,
        APPOINTMENT_TIME,
        APPOINTMENT_TYPE,
        APPOINTMENT_STATUS,
        CHECK_IN_TIME::TIME AS CHECK_IN_TIME,
        CHECK_OUT_TIME::TIME AS CHECK_OUT_TIME,
        WAIT_TIME_MINUTES,
        CONSULTATION_DURATION_MINUTES,
        REASON_FOR_VISIT,
        NOTES,
        FOLLOW_UP_REQUIRED,
        CASE    
            WHEN NEXT_APPOINTMENT_DATE<=CURRENT_DATE THEN NEXT_APPOINTMENT_DATE
            ELSE NULL
        END NEXT_APPOINTMENT_DATE,
        PAYMENT_STATUS,
        PAYMENT_AMOUNT
    FROM
        {{ ref("bronze_appointments_history")}}