SELECT
    DOCTOR_ID,
    CASE    
        WHEN FULL_NAME IS NULL THEN 'Unknown'
        ELSE TRIM(FULL_NAME)
    END AS FULL_NAME,
    SPECIALIZATION,
    QUALIFICATION,
    LICENSE_NUMBER,
    YEARS_OF_EXPERIENCE,
    PRIMARY_BRANCH_ID,
    SECONDARY_BRANCH_ID,
    CASE
        WHEN LENGTH(REPLACE(PHONE,'-',''))=10 THEN PHONE
        ELSE NULL
    END AS PHONE,
    EMAIL,
    CASE    
        WHEN HIRE_DATE<=CURRENT_DATE THEN HIRE_DATE
        ELSE NULL
    END AS HIRE_DATE,
    CASE 
        WHEN LOWER(EMPLOYMENT_STATUS) IN ('active','a') THEN 'Active'
        WHEN LOWER(EMPLOYMENT_STATUS) IN ('inactive','i') THEN 'Inactive'
        ELSE NULL
    END EMPLOYMENT_STATUS,
    CONSULTATION_FEE,
    RATING,
    LANGUAGES_SPOKEN,
    WORKING_HOURS,
    CASE 
        WHEN EMERGENCY_AVAILABILITY IN ('T','true','TRUE') THEN 'True'
        WHEN EMERGENCY_AVAILABILITY IN ('F','false','FALSE') THEN 'False'
        ELSE 'null'
    END AS EMERGENCY_AVAILABILITY
FROM {{ref("bronze_medical_practioners")}}
WHERE ID_VALIDATION='valid'