healthcare_dbt:
    target: dev
    outputs:
        dev:
            type: snowflake

            account: OLQAHMP-WG32005

            user: VIVEKPANTHII

            role: ACCOUNTADMIN
            database: MYDB
            warehouse: HEALTHCARE
            schema: BRONZE
            threads: 1
            password: "#Newton66564506"
